services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: caix
      POSTGRES_PASSWORD: caix
      POSTGRES_DB: caix

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
